# Generated by Django 6.0.5 on 2026-06-02 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('merchant_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transport'), ('RETAIL', 'Retail'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health & Medical'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'merchants',
                'indexes': [models.Index(fields=['category'], name='idx_merchant_category'), models.Index(fields=['merchant_code'], name='idx_merchant_code'), models.Index(fields=['country'], name='idx_merchant_country')],
            },
        ),
    ]
