# Generated by Django 6.0.5 on 2026-06-02 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('WALLET', 'Wallet')], default='SAVINGS', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number_hash', models.CharField(max_length=64)),
                ('last_four', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express')], default='VISA', max_length=10)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('is_contactless', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
