# Generated by Django 6.0.5 on 2026-06-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_transaction_status_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='accounts.transaction'),
        ),
    ]
