# Generated by Django 6.0.5 on 2026-06-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_created_at'),
    ]

    operations = [
        migrations.RunSQL(
            # UNIQUE         -> no two rows share an email (the real guarantee)
            # COLLATE NOCASE -> case-insensitive (Alice@ == alice@), SQLite's way
            # WHERE email<>''-> partial index: blank emails exempt, never collide
            sql="""
                CREATE UNIQUE INDEX uniq_user_email_ci
                ON auth_user (email COLLATE NOCASE)
                WHERE email <> '';
            """,
            reverse_sql="DROP INDEX IF EXISTS uniq_user_email_ci;",
        ),
    ]