import uuid

from django.db import models
from django.db.models import Q

from utils.choices import Currency, TransactionStatus, TransactionType
from utils.timestamped import TimeStampedModel
# from .managers import TransactionManager


class Transaction(TimeStampedModel):
    """
    The core financial event. Records money moving between accounts.

    Design principles enforced here:

    1. IMMUTABLE
       Transactions are never updated after creation except for status
       transitions (pending → completed/failed). If a transaction must
       be undone, a new REVERSAL transaction is created and linked via
       reversal_of. This preserves the full audit trail.

    2. IDEMPOTENT
       reference_id is a client-generated UUID unique key. Before creating
       a transaction, the service layer checks if reference_id already exists.
       If it does, the existing record is returned — not a duplicate created.
       This prevents double-charges on network retries.

    3. NULLABLE ACCOUNTS (external money movement)
       from_account is nullable → supports top-ups from an external source
       (e.g. bank transfer in). No internal "from" account exists.
       to_account is nullable → supports withdrawals to an external destination
       (e.g. cash out). No internal "to" account exists.

    4. SELF-REFERENCING FK (reversal chain)
       reversal_of points to the original transaction that this one reverses.
       OneToOneField ensures one transaction can only be reversed once.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Idempotency key — generated by the caller (API client or service layer)
    reference_id = models.UUIDField(unique=True, default=uuid.uuid4, db_index=True)

    from_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="outgoing_transactions",
        null=True,
        blank=True,
    )
    to_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="incoming_transactions",
        null=True,
        blank=True,
    )
    merchant = models.ForeignKey(
        "merchants.Merchant",
        on_delete=models.SET_NULL,
        related_name="transactions",
        null=True,
        blank=True,
    )
    card = models.ForeignKey(
        "accounts.Card",
        on_delete=models.SET_NULL,
        related_name="transactions",
        null=True,
        blank=True,
    )

    # Self-referencing: if this transaction reverses another, point to it.
    # OneToOneField ensures each original can only be reversed once.
    reversal_of = models.OneToOneField(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reversed_by",
    )

    amount   = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(
        max_length=3,
        choices=Currency.choices,
        default=Currency.BDT,
    )
    transaction_type = models.CharField(
        max_length=15,
        choices=TransactionType.choices,
    )
    status = models.CharField(  
        max_length=10,
        choices=TransactionStatus.choices,
        default=TransactionStatus.PENDING,
    )

    description  = models.TextField(blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    # objects = TransactionManager()

    class Meta:
        db_table = "transactions"
        indexes = [
            models.Index(fields=["status"],           name="idx_txn_status"),
            models.Index(fields=["transaction_type"], name="idx_txn_type"),
            models.Index(fields=["currency"],         name="idx_txn_currency"),
            # Composite: dashboard query — "completed transactions this month"
            models.Index(fields=["status", "created_at"], name="idx_txn_status_created"),
            # Composite: account statement query
            models.Index(fields=["from_account", "created_at"], name="idx_txn_from_account_date"),
            models.Index(fields=["to_account",   "created_at"], name="idx_txn_to_account_date"),
        ]
        constraints = [
            # Amount must always be a positive value
            models.CheckConstraint(
                condition=Q(amount__gt=0),
                name="chk_txn_amount_positive",
            ),
            # Prevent self-transfers: from and to account must differ.
            # The OR conditions allow nulls (external top-ups / withdrawals).
            models.CheckConstraint(
                    condition=(~Q(from_account=models.F("to_account"))
                    | Q(from_account__isnull=True)
                    | Q(to_account__isnull=True)
                    ),
                name="chk_txn_accounts_differ",
            ),
        ]
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"[{self.status}] {self.get_transaction_type_display()} | "
            f"{self.amount} {self.currency} | ref: {self.reference_id}"
        )

    @property
    def is_completed(self):
        return self.status == TransactionStatus.COMPLETED

    @property
    def is_pending(self):
        return self.status == TransactionStatus.PENDING

    @property
    def is_reversible(self):
        """
        A transaction can only be reversed if it's completed
        and hasn't already been reversed.
        """
        return self.is_completed and not hasattr(self, "reversed_by")   