# Generated by Django 6.0.5 on 2026-06-02 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('BDT', 'Bangladeshi Taka'), ('USD', 'US Dollar')], default='BDT', max_length=3)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('TOP_UP', 'Top Up'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.card')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='accounts.account')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchants.merchant')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='transactions.transaction')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_txn_status'), models.Index(fields=['transaction_type'], name='idx_txn_type'), models.Index(fields=['currency'], name='idx_txn_currency'), models.Index(fields=['status', 'created_at'], name='idx_txn_status_created'), models.Index(fields=['from_account', 'created_at'], name='idx_txn_from_account_date'), models.Index(fields=['to_account', 'created_at'], name='idx_txn_to_account_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_txn_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('from_account', models.F('to_account')), _negated=True), ('from_account__isnull', True), ('to_account__isnull', True), _connector='OR'), name='chk_txn_accounts_differ')],
            },
        ),
    ]
